name:                haskell-tonatona-mod
version:             0.1.0.0
github:              boygao1992/haskell-tonatona-mod
license:             BSD3
author:              wenbo
maintainer:          wg2313@columbia.edu
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/boygao1992/haskell-tonatona-mod#readme>

dependencies:
- base >= 4.11 && < 10
- http-types >= 0.12
- optparse-applicative >= 0.14
- rio >= 0.1.8.0
- servant >= 0.15
- servant-server >= 0.15
- wai >= 3.2
- wai-extra >= 3.0
- warp >= 3.2
- transformers >= 0.5
- beam-core >= 0.8
- beam-postgres
- beam-mysql
- mysql >=0.1 && <0.2
- bytestring >= 0.10
- containers >= 0.6
- newtype-generics >= 0.5
- aeson >= 1.4
- http-types >= 0.12
- http-client >= 0.6




ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-signatures # NOTE for lenses

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- ExplicitForAll
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

executables:
  haskell-tonatona-mod-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - haskell-tonatona-mod
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  haskell-tonatona-mod-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - haskell-tonatona-mod
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
