source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in ruby_sinatra_starter.gemspec
gemspec

gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
