name: tonalude
version: "0.1.1.0"
category: "Control, Library, Tonatona"
synopsis: A standard library for Tonatona framework.
description:
  Tonaparser provides a way to pass runtime configurations.
  This library is supposed to be used with @tonatona@.
  The Tonalude module works as a prelude replacement for Tonatona framework, providing more functionality and types out of the box than the standard prelude (such as common data types like ByteString and Text), as well as removing common "gotchas", like partial functions and lazy I/O.
license: "MIT"
author: "Kadzuya Okamoto"
copyright: "2018 Kadzuya Okamoto"
maintainer: "arow.okamoto+github@gmail.com"

extra-source-files:
  - README.md

ghc-options: -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10
  - rio >= 0.1.5
  - unliftio >= 0.2.4

library:
  source-dirs:
    - src
  other-modules:
    - Tonalude.Prelude.Display
    - Tonalude.Prelude.IO
    - Tonalude.Prelude.Reexports
    - Tonalude.Prelude.Renames
    - Tonalude.Prelude.RIO
    - Tonalude.Prelude.Text
    - Tonalude.Prelude.Trace

tests:
  spec:
    main: "Spec.hs"
    other-modules: []
    source-dirs:
      - test
  doctest:
    main: "DocTest.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - doctest
      - Glob

github: tonatona-project/tonatona
